FROM debian:latest@sha256:181ecf074fdc824a42be4f84a7be2eba33c4ac298ae1ab15a4e69ed052bd9ec0

RUN apt-get -q update \
		&& apt-get install -y git-core build-essential mercurial gcc libc6-dev curl python python-dev python-pip python-setuptools wget ca-certificates libssl-dev  --no-install-recommends \
		&& apt-get clean \
		&& rm -rf /var/lib/apt/lists/*

# Install AWS CLI
RUN pip install awscli

COPY . /
