FROM alpine:latest@sha256:4f4ba248d8a2c90a6e52ffdfc194181f7617f9ddaca348d4c550a6b354fc7c2a

RUN apk add --no-cache bash git build-base gcc curl python python-dev py-pip wget ca-certificates musl-dev openssl coreutils

# Install AWS CLI
RUN pip install awscli

COPY . /
