FROM alpine:latest@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

RUN apk add --no-cache bash git build-base gcc curl python python-dev py-pip wget ca-certificates musl-dev openssl coreutils

# Install AWS CLI
RUN pip install awscli

COPY . /
