FROM debian:latest@sha256:fac46bff2e02f51425b6e33b0e1169f55dfb053d83511ca28aa50c09fd5ed7a4

RUN apt-get -q update \
		&& apt-get install -y git-core build-essential mercurial gcc libc6-dev curl python python-dev python-pip python-setuptools wget ca-certificates libssl-dev  --no-install-recommends \
		&& apt-get clean \
		&& rm -rf /var/lib/apt/lists/*

# Install AWS CLI
RUN pip install awscli

COPY . /
