FROM debian:latest@sha256:1de1fcf32a035452eb3a2c99926a9988509f177b3c99efab609700297d2076bf

RUN apt-get -q update \
		&& apt-get install -y git-core build-essential mercurial gcc libc6-dev curl python python-dev python-pip python-setuptools wget ca-certificates libssl-dev  --no-install-recommends \
		&& apt-get clean \
		&& rm -rf /var/lib/apt/lists/*

# Install AWS CLI
RUN pip install awscli

COPY . /
