FROM alpine:latest@sha256:f5064d3e5f88c467c714509f491853ab2d951932c5cad699c0cb969dcec6f3b4

RUN apk add --no-cache bash git build-base gcc curl python python-dev py-pip wget ca-certificates musl-dev openssl coreutils

# Install AWS CLI
RUN pip install awscli

COPY . /
